---
# site.yml

- name: Fedora laptop setup
  hosts: localhost
  # connection: local
  gather_facts: true

  vars_files:
  - vars/main.yml

  tasks:

  - name: Install and/or update repositories
    ansible.builtin.yum:
      name: "{{ item.name }}"
      baseurl: "{{ item.baseurl }}"
      enabled: "{{ item.enabled }}"
      gpgcheck: no
      ip_resolve: 4
      state: "{{ item.state }}"
    loop: "{{ repositories }}"